apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: openTelemetryCluster
  region: us-east-1
  version: "1.31" # The version of kubernetes to use  

# To provide custom VPC Configurations 
# vpc:
#   id : "" #optional
#   cidr: "" #optional 
#   nat:
#     gateway: HighlyAvailable # Building a NAT in each availabiliy zone
#   subnets:
#     public: 
#       us-east-1a:
#         id:
#         cidr: "" #optional 
#       us-east-1b:
#         id:
#         cidr: "" #optional 
    
#     private:
#       us-east-1a: 
#         id:
#         cidr: "" #optional
#       us-east-1b:
#         id:
#         cidr: "" #optional
   

managedNodeGroups:
  - name: ng-1
    labels: { role: workers }
    instanceType: t3.large
    desiredCapacity: 3
    volumeSize: 20 
    minSize: 2
    maxSize: 4
    ssh:
      allow: true
      publicKeyName : SSH1 # The access key should be present in the same region as the EKS Cluster
    # privateNetworking: true  # Ensures nodes are in private subnets
    # subnets:
    #   - us-east-1a
    #   - us-east-1b



