name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Adjust to your default branch if necessary
    paths:
      - 'opentelemetry-demo/src**'
      - 'phase2/deployment/open-telemetry/**'
  workflow_dispatch:  # Optional: allows manual triggering


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker images
        run: |
          # Build and push Image for accounting service if changed
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^opentelemetry-demo/src/accountingservice/'; then
            echo "Building and pushing accounting service..."
            docker build -f ./open-telemetry-demo/src/accountingservice/Dockerfile -t ${{ secrets.ECR_REPOSITORY_ACCOUNTING_SERVICE }}:latest ./open-telemetry-demo
            docker push ${{ secrets.ECR_REPOSITORY_ACCOUNTING_SERVICE }}:latest
          fi

          # Build and push adservice if changed
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^opentelemetry-demo/src/adservice/'; then
            echo "Building and pushing ad service..."
            docker build -t ${{ secrets.ECR_REPOSITORY_AD_SERVICE }}:latest adservice
            docker push ${{ secrets.ECR_REPOSITORY_AD_SERVICE }}:latest
          fi

          # Build and push cart service if changed
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^opentelemetry-demo/src/cartservice/'; then
            echo "Building and pushing cart service..."
            docker build -t ${{ secrets.ECR_REPOSITORY_CART_SERVICE }}:latest adservice
            docker push ${{ secrets.ECR_REPOSITORY_CART_SERVICE }}:latest
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install kubectl
        run: |
          sudo curl -LO "https://dl.k8s.io/release/v1.30.2/bin/linux/amd64/kubectl" # Change version and OS as needed
          sudo chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name openTelemetryCluster --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          # Deploy accounting service if changed

          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^opentelemetry-demo/src/accountingservice/'; then
            echo "Deploying accounting service..."
            kubectl set image deployment/opentelemetry-demo-accountingservice accountingservice=${{ secrets.ECR_REPOSITORY_ACCOUNTING_SERVICE }}:latest
            kubectl rollout status deployment/opentelemetry-demo-accountingservice
          fi

          # Deploy adservice if changed
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q opentelemetry-demo/src/adservice/ then
            echo "Deploying ad service..."
            kubectl set image deployment/opentelemetry-demo-adservice adservice=${{ secrets.ECR_REPOSITORY_AD_SERVICE }}:latest
            kubectl rollout status deployment/opentelemetry-demo-adservice
          fi

          # Deploy cart service if changed
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q opentelemetry-demo/src/cartservice/ then
            echo "Deploying cart service..."
            kubectl set image deployment/opentelemetry-demo-cartservice cartservice=${{ secrets.ECR_REPOSITORY_CART_SERVICE }}:latest
            kubectl rollout status deployment/opentelemetry-demo-cartservice
          fi

      - name: Restart Pods 
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^opentelemetry-demo/src/accountingservice/'; then
            echo "Restarting accounting service pods"
            kubectl rollout restart deployment/opentelemetry-demo-accountingservice
          fi

          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^opentelemetry-demo/src/adservice/'; then
            echo "Restarting ad service pods"
            kubectl rollout restart deployment/opentelemetry-demo-adservice
          fi

          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^opentelemetry-demo/src/cartservice/'; then
            echo "Restarting cart service pods"
            kubectl rollout restart deployment/opentelemetry-demo-cartservice
          fi