# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Integration Tests


on:
  push:
    branches:
      - main # Adjust to your default branch if necessary
  workflow_dispatch:
  
# on:
#   pull_request_review:
#     types:
#       - submitted

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: "Run Integration tests"
    # if: github.event.review.state == 'APPROVED'
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: run tracetesting
        run: |
          make -f ./open-telemetry-demo/Makefile build && make -f ./open-telemetry-demo/Makefile run-tracetesting
