# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Integration Tests


# on:
#   push:
#     branches:
#       - main # Adjust to your default branch if necessary
#   workflow_dispatch:
  
on:
  pull_request_review:
    types:
      - submitted

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: "Run Integration tests"
    if: github.event.review.state == 'APPROVED'
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: Load environment variables from .env file
        run: |
          cd ./open-telemetry-demo

          # Check if the .env file exists
          if [ ! -f .env ]; then
            echo ".env file not found!"
            exit 1
          fi

          # Read each line from the .env file
          while IFS='=' read -r key value; do
            # Skip empty lines and comments (lines starting with '#')
            if [[ -z "$key" || "$key" =~ ^# ]]; then
              continue
            fi
            
            echo "Loaded: $key=$value"

            # Export the environment variable
            export "$key"="$value"

          done < .env
          
  

      - name: run tracetesting
        run: |
          cd ./open-telemetry-demo && make build && docker system prune -f && make run-tracetesting
